select * from person;
SELECT * FROM CAR where car_id = '6778796693';

SELECT CAR_ID, CAR_NAME, CAR_MAKE_YEAR, CAR_PRICE, CAR_MAKER_NAME
FROM CAR C JOIN CAR_MAKER CM
ON C.CAR_MAKER_CODE = CM.CAR_MAKER_CODE;

UPDATE CAR SET CAR_PRICE = TRUNC(CAR_PRICE * 0.9,0) WHERE CAR_PRICE >= (SELECT AVG(CAR_PRICE) FROM CAR);

use scott;
select * from student;

